<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE exhibitions [
  <!ELEMENT exhibitions (exhibition+)>
  <!ELEMENT exhibition (title, description, visitors, showpieces)>
  <!ATTLIST exhibition exhibitionId CDATA #REQUIRED>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT visitors (visitor*)>
  <!ATTLIST visitor id CDATA #REQUIRED>
  <!ELEMENT showpieces (showpiece*)>
  <!ATTLIST showpiece id CDATA #REQUIRED>
]>
<exhibitions>
  <exhibition exhibitionId="209">
    <title>Books</title>
    <description>Exhibition on new Books</description>
    <visitors>
      <visitor id="12345" />
    </visitors>
    <showpieces>
      <showpiece id="00001" />
    </showpieces>
  </exhibition>
</exhibitions>
