=== leokelly16/NationalLibraryXML/visitor.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Visitors (Visitor+)>

<!ELEMENT Visitor (Visitor.name, Visitor.email)>
<!ATTLIST Visitor
    id CDATA #REQUIRED
>

<!ELEMENT Visitor.name (#PCDATA)>
<!ELEMENT Visitor.email (#PCDATA)>

=== leokelly16/NationalLibraryXML/visitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Visitors SYSTEM "visitor.dtd">
<Visitors>
  <Visitor id="72981">
    <Visitor.name>Ellie Hartman</Visitor.name>
    <Visitor.email>ehartman@gmail.com</Visitor.email>
  </Visitor>
  <Visitor id="72739">
    <Visitor.name>James O'Connor</Visitor.name>
    <Visitor.email>connor.james@gmail.com</Visitor.email>
  </Visitor>
    <Visitor id="52791">
    <Visitor.name>Patrick Kineely</Visitor.name>
    <Visitor.email>kinpatrick02@gmail.com</Visitor.email>
  </Visitor>
    <Visitor id="72901">
    <Visitor.name>Milly Donnolly</Visitor.name>
    <Visitor.email>millydon98@gmail.com</Visitor.email>
  </Visitor>
</Visitors>
